# Generated by Django 4.2.4 on 2023-08-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventEmails', '0002_emailtemplates_emaillogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(null=True),
        ),
    ]
